name: Build and Push Arch Linux DolphinOS installation ISO builder images

on:
  push:
    paths:
      - 'arch-repo-image/**'
      - '.github/workflows/build_arch_repo_image.yaml'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" #rebuilds every week

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Log in into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository
        id: repo
        run: echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./arch-repo-image
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo }}/arch_repo__builder_image:latest
            ghcr.io/${{ steps.repo.outputs.repo }}/arch_repo__builder_image:${{ github.sha }}
